### ISSUE TITLE
TypeError: Parameter 'subscription_id'

### ISSUE THREAD

**Issue by yokawasa** [yokawasa/azure-ssh-config#1]
Got the following error message and the command execution failed even if subscription_id value is actually assigned as string

> $ ./azuresshconfig.py
> Traceback (most recent call last):
>   File "./azuresshconfig.py", line 341, in <module>
>     main()
>   File "./azuresshconfig.py", line 293, in main
>     credentials, cconf.subscription_id)
>   File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute_management_client.py", line 132, in **init**
>     self.config = ComputeManagementClientConfiguration(credentials, subscription_id, accept_language, long_running_operation_retry_timeout, generate_client_request_id, base_url, fi
> lepath)
>   File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute_management_client.py", line 63, in **init**
>     raise TypeError("Parameter 'subscription_id' must be str.")
> TypeError: Parameter 'subscription_id' must be str.

**Comment by yokawasa** [comment]
fixup the issue - See [diff](https://github.com/yokawasa/azure-ssh-config/commit/afaa264e044a6e2b049f0443dd775bfc9f9dda67)
